### ISSUE TITLE
Adding duplicate comment when deleting a preview

### ISSUE THREAD

**Issue by stephenmathieson** [yinlinchen/amplify-preview-actions#13]
First off, thank you for this! Getting deployment previews on OSS repos is super helpful!

---

**Describe the bug**
The action adds a comment when _deleting_ a preview.

**To Reproduce**
```yaml
name: PR preview cleanup

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setenv
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      - uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: ${{ steps.setenv.outputs.BRANCH_NAME }}
          amplify_command: delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: d1gko6en628vir
          AWS_REGION: us-east-1
```

**Expected behavior**
The preview is deleted, no comment is created.

**Screenshots**
Duplicate comment (the 2nd is result of deletion of a preview):

![image](https://user-images.githubusercontent.com/571265/151599247-7acc1d85-5cbb-4b71-8015-3ccdad958a20.png)

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
