### ISSUE TITLE
getting `curl: no URL specified!` when running workflow

### ISSUE THREAD

**Issue by alez007** [yinlinchen/amplify-preview-actions#15]
**Describe the bug**
Full error is:
```
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

but the actual preview is being created or deleted

**Additional context**
current workflow
```
name: Builds a Amplify Preview
on:
  issue_comment:
    types:
      - created

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }}-${{github.event.issue.number}}'
  cancel-in-progress: true

jobs:
  amplify-preview:
    name: "Amplify Preview"
    runs-on: ubuntu-latest
    environment: CI
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'preview' }}
    steps:
      - name: React to comment
        uses: dkershner6/reaction-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commentId: ${{ github.event.comment.id }}
          reaction: "rocket"
      - name: Node set up
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
      - name: Find out PR ref
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.refs.outputs.head_ref }}
      - name: Remove existent PR preview
        uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: ${{ steps.refs.outputs.head_ref }}
          amplify_command: delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: ${{ secrets.AMPLIFY_APPID }}
          BackendEnvARN: ${{ secrets.AMPLIFY_BACKEND_ENV_ARN }}
          AWS_REGION: 'eu-west-2'
      - name: Deploy PR preview
        uses: yinlinchen/amplify-preview-actions@master
        with:
          branch_name: ${{ steps.refs.outputs.head_ref }}
          amplify_command: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AmplifyAppId: ${{ secrets.AMPLIFY_APPID }}
          BackendEnvARN: ${{ secrets.AMPLIFY_BACKEND_ENV_ARN }}
          AWS_REGION: 'eu-west-2'
```

**Comment by alez007** [comment]
closing this as this project is only meant to work for pull_request events, therefore it's using pull_request event comments url to submit comments in PR and that's why this error occurs, any other event, like mine (issue_comment), has that info empty; 

if anyone stumbles upon this, here's a copy paste example of an amplify deploy job that will also delete old branch if it exists and it won't fail for subsequent triggers

```
name: Builds a Amplify Preview
on:
  issue_comment:
    types:
      - created

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }}-${{github.event.issue.number}}'
  cancel-in-progress: true

env:
  AMPLIFY_APPID: ${{ secrets.AMPLIFY_APPID }}
  AWS_REGION: 'eu-west-2'

jobs:
  amplify-create-preview:
    name: "Amplify Preview"
    runs-on: ubuntu-latest
    environment: CI
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'preview' }}
    steps:
      - name: React to comment
        uses: dkershner6/reaction-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commentId: ${{ github.event.comment.id }}
          reaction: "rocket"
      - name: Find out PR ref
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Python set up
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install AWS Cli
        env:
          AWSCLI_VERSION: '1.18.14'
        run: |
          pip install --quiet --no-cache-dir awscli==${AWSCLI_VERSION}
      - name: Install CURL
        run: sudo apt-get install -y curl
      - name: Configure AWS
        run: |
          aws configure <<-EOF > /dev/null 2>&1
          ${{ secrets.AWS_ACCESS_KEY_ID }}
          ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          $AWS_REGION
          text
          EOF
      - name: Get existent branch info
        id: get-branch
        run: aws amplify get-branch --app-id=$AMPLIFY_APPID --branch-name=${{ steps.refs.outputs.head_ref }}
        continue-on-error: true
      - name: Delete branch if exists
        if: steps.get-branch.outcome == 'success'
        run: aws amplify delete-branch --app-id=$AMPLIFY_APPID --branch-name=${{ steps.refs.outputs.head_ref }}
      - name: Create amplify preview
        run: |
          aws amplify create-branch --app-id=$AMPLIFY_APPID --branch-name=${{ steps.refs.outputs.head_ref }} --backend-environment-arn=${{ secrets.AMPLIFY_BACKEND_ENV_ARN }} --region=$AWS_REGION
          aws amplify start-job --app-id=$AMPLIFY_APPID --branch-name=${{ steps.refs.outputs.head_ref }} --job-type=RELEASE --region=$AWS_REGION
```
