### ISSUE TITLE
Update Branch

### ISSUE THREAD

**Issue by sean-smith** [yinlinchen/amplify-preview-actions#8]
I'd like to suggest a new feature, "update" that's triggered when a PR is updated and the branch already exists. Currently this will break the current workflow since it'll try to re-create the branch and break. See 

To implement it, it looks like it'd be as simple as adding an if condition [here](https://github.com/yinlinchen/amplify-preview-actions/blob/master/entrypoint.sh#L49) to check if the branch exists. If it does, skip creation and run `start-job`.

**Comment by yinlinchen** [comment]
@sean-smith Can you describe in what scenario(workflow) you will encounter this? Update an existing PR will update the existing deployed branch preview in the Amplify console. It will not re-create the existing one and break.

**Comment by sean-smith** [comment]
Hmm ok I think I'm at fault then, I'm using the following `pr.yaml`, you'll note I removed the line `types: [review_requested]` which causes it to re-run on any PR action. I didn't know it would automatically run on new branch updates.

```yaml
name: 'Amplify PR Preview'
on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for review')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: set branchname env
      id: setenvname
      run: |
        # use GITHUB_HEAD_REF that is set to PR source branch
        echo "##[set-output name=setbranchname;]$(echo ${GITHUB_HEAD_REF})"
    - name: deploy PR preview
      uses: yinlinchen/amplify-preview-actions@master
      with:
        branch_name: ${{ steps.setenvname.outputs.setbranchname }}
        amplify_command: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        AmplifyAppId: ${{ secrets.AMPLIFYAPPID }}
        BackendEnvARN: ${{ secrets.BACKENDENVARN }}
        AWS_REGION: 'us-east-1'
```

See https://github.com/aws-samples/aws-hpc-tutorials/pull/23
